version: '3.8'
services:
  webapp:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    container_name: mssql
    build:
      context: .
      dockerfile: db.Dockerfile
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "funky-penguin-cafe-train8"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"